module.exports = {
    queues: {
        TRANSCRIBE_VIDEO_QUEUE: 'TRANSCRIBE_VIDEO_QUEUE',
        TRANSCRIBE_FINISH_QUEUE: 'TRANSCRIBE_FINISH_QUEUE',
        CONVERT_VIDEO_TO_ARTICLE_QUEUE: 'CONVERT_VIDEO_TO_ARTICLE_QUEUE',
        EXPORT_ARTICLE_TRANSLATION: `EXPORT_ARTICLE_TRANSLATION`,
        EXPORT_ARTICLE_TRANSLATION_FINISH: `EXPORT_ARTICLE_TRANSLATION_FINISH`,
    }
}